In [1]:
# !pip install fastai -U

## Image classification with Convolutional Neural Networks

In [2]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
# This file contains all the main external libs we'll use
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [4]:
# PATH = "data/dogscats/"
PATH = "lta/"
sz=224
# arch=vgg16
# arch=vgg19
arch=resnet50
# bs=16
bs=32

In [5]:
# Uncomment the below if you need to reset your precomputed activations
# !rm -rf {PATH}tmp

In [6]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))

In [7]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [8]:
# learn.lr_find()
# learn.sched.plot()

In [9]:
learn.fit(0.01, 3, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[0.      1.1426  0.78629 0.5    ]                        
[1.      0.81899 0.70029 0.53571]                        
[2.      0.85809 0.59667 0.64286]                        



In [9]:
learn.fit(1e-2, 3, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[0.      1.1426  0.78629 0.5    ]                        
[1.      0.81899 0.70029 0.53571]                        
[2.      0.85809 0.59667 0.64286]                        



In [10]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)

In [11]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [12]:
# learn.fit(1e-2, 2)
learn.fit(1e-2, 3)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[0.      0.67827 0.61736 0.67857]                        
[1.      0.69872 0.41432 0.82143]                        
[2.      0.53368 0.51282 0.75   ]                        



In [13]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)
# probs = np.mean(np.exp(log_preds),0)
# accuracy_np(probs,y)

0.75

---

In [14]:
learn.precompute=False
# learn.precompute=True

In [15]:
learn.fit(1e-2, 2, cycle_len=1)
# learn.fit(1e-3, 2, cycle_len=1)
# learn.fit(1e-2, 6, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=2), HTML(value='')))

[0.      0.45338 0.39975 0.78571]                        
[1.      0.38167 0.34946 0.82143]                        



In [16]:
learn.unfreeze()

In [17]:
# lr=np.array([1e-4,1e-3,1e-2])
lr=np.array([1e-7,1e-5,1e-3])

In [18]:
# learn.fit(lr, 4, cycle_len=1)
learn.fit(lr, 2, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=2), HTML(value='')))

[0.      0.60122 0.38249 0.85714]                        
[1.      0.62895 0.46856 0.82143]                        



In [19]:
learn.fit(lr, 3, cycle_len=1, cycle_mult=2)
# learn.fit(lr, 2, cycle_len=1, cycle_mult=2)

HBox(children=(IntProgress(value=0, description='Epoch', max=7), HTML(value='')))

[0.      0.47437 0.51052 0.85714]                        
[1.      0.48467 0.49912 0.89286]                        
[2.      0.56253 0.46166 0.78571]                        
[3.      0.60052 0.45426 0.82143]                        
[4.      0.60438 0.45751 0.78571]                        
[5.      0.60847 0.46636 0.78571]                        
[6.      0.59428 0.45017 0.78571]                        



In [24]:
learn.fit(lr, 2, cycle_len=3)

HBox(children=(IntProgress(value=0, description='Epoch', max=6), HTML(value='')))

[0.      0.55031 0.39359 0.89286]                        
[1.      0.51223 0.391   0.89286]                        
[2.      0.54316 0.3953  0.89286]                        
[3.      0.58739 0.3962  0.85714]                        
[4.      0.56977 0.39997 0.85714]                        
[5.      0.54119 0.39088 0.89286]                        



In [25]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)
# probs = np.mean(np.exp(log_preds),0)
# accuracy_np(probs,y)

0.9285714285714286

---