In [1]:
!pip install fastai -U

Requirement already up-to-date: fastai in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages
Requirement already up-to-date: ipykernel in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: pytz in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: entrypoints in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: jupyter-client in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: Jinja2 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: nbformat in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from fastai)
Requirement already up-to-date: MarkupSafe in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages 

Requirement already up-to-date: cliff<2.9,>=2.8.0 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: cssselect<1.1,>=1.0.1 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: beautifulsoup4<4.7,>=4.6.0 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: MechanicalSoup<0.9,>=0.7.0 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: configparser in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: progressbar2<3.35,>=3.34.3 in /home/iss-user/anaconda3/envs/iss-env-py3/lib/python3.6/site-packages (from kaggle-cli->fastai)
Requirement already up-to-date: lxml<4.1,>=4.0.0 in /home/iss-user/anaconda3/env

## Image classification with Convolutional Neural Networks

In [88]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [103]:
# This file contains all the main external libs we'll use
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [104]:
# PATH = "data/dogscats/"
PATH = "lta/"
sz=224
arch=vgg16
bs=16

In [105]:
# Uncomment the below if you need to reset your precomputed activations
# !rm -rf {PATH}tmp

In [106]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))

In [107]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [108]:
# learn.lr_find()
# learn.sched.plot()

In [109]:
learn.fit(0.01, 6, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=6), HTML(value='')))

[0.      0.75559 0.77744 0.5    ]                        
[1.      0.82765 0.69054 0.53571]                        
[2.      0.69016 0.61768 0.60714]                        
[3.      0.73677 0.55683 0.75   ]                        
[4.      0.63456 0.54039 0.64286]                        
[5.      0.59349 0.52521 0.75   ]                        



In [110]:
learn.fit(0.001, 6, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=6), HTML(value='')))

[0.      0.37008 0.51529 0.71429]                        
[1.      0.36283 0.51039 0.75   ]                        
[2.      0.52075 0.50817 0.67857]                        
[3.      0.46542 0.51016 0.67857]                        
[4.      0.45013 0.47766 0.71429]                        
[5.      0.40968 0.48127 0.67857]                        



In [111]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)

In [113]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True)
# learn = ConvLearner.pretrained(arch, data, precompute=False)

In [114]:
# learn.fit(1e-2, 2)
learn.fit(1e-3, 3)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[0.      0.9544  0.64868 0.57292]                        
[1.      0.79977 0.63714 0.6875 ]                        
[2.      0.75338 0.56948 0.80208]                        



In [115]:
# learn.fit(1e-2, 2)
learn.fit(1e-2, 6)

HBox(children=(IntProgress(value=0, description='Epoch', max=6), HTML(value='')))

[0.      0.52557 0.47721 0.84375]                        
[1.      0.43665 0.37538 0.78125]                        
[2.      0.35036 0.29775 0.86458]                        
[3.      0.28075 0.29128 0.82292]                        
[4.      0.25467 0.31716 0.875  ]                        
[5.      0.25453 0.34047 0.84375]                        



In [116]:
# learn.fit(1e-2, 2)
learn.fit(1e-3, 3)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[0.      0.0954  0.34888 0.875  ]                         
[1.      0.12323 0.36889 0.84375]                         
[2.      0.09476 0.34643 0.875  ]                         



In [118]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)
# probs = np.mean(np.exp(log_preds),0)
# accuracy_np(probs,y)

0.8571428571428571

---

In [23]:
learn.precompute=False
# learn.precompute=True

In [ ]:
# learn.fit(1e-2, 2, cycle_len=1)
learn.fit(1e-2, 6, cycle_len=1)

In [ ]:
learn.unfreeze()

In [ ]:
lr=np.array([1e-4,1e-3,1e-2])

In [ ]:
learn.fit(lr, 4, cycle_len=1)
# learn.fit(lr, 2, cycle_len=1)

In [ ]:
learn.fit(lr, 3, cycle_len=1, cycle_mult=2)

In [ ]:
learn.fit(lr, 1, cycle_len=3)

---

In [73]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)
# probs = np.mean(np.exp(log_preds),0)
# accuracy_np(probs,y)

0.8571428571428571

---